<?php

function ff_title($nid, $type = "", $published = "") {
   /* 
     Returns the name of the node provided in $nid
     $nid = Node ID of item to lookup
     $type = If provided, limit search to passed content type (Machine Readable)
     $published = Returns title of nid regardless of publication status. If provided, limit search to 1 Published, or 0 Unpublished
      
   */
   
   $s = "SELECT title FROM {node} WHERE nid=%d";
   $vars[] = $nid;
   
   if ($type != "") { 
     $s .= " AND type = '%s'";
     $vars[] = $type;
   }
   
   if ($published != "") {
     $s .= " AND status = %d";
     $vars[] = $published;
   }
   
   // do the query
   $r = db_query($s, $vars);
   
   if (db_affected_rows($r)==1) {
     return db_result($r);
   } else {
     return FALSE;
   }
}

function ff_term($tid, $vid = "") {
  /* 
    Returns the term name based on $tid with optional $vid 
  */
  $s = "SELECT name FROM {term_data} WHERE tid = %d";
  $vars[] = $tid;
  
  if ($vid != "") {
    $s .= " AND vid = %d";
    $vars[] = $vid;
  }
  
  // do the query
  $r = db_query($s, $vars);
  if (db_affected_rows($r)==1) {
    return db_result($r);
  } else {
    return FALSE;
  }
  
}

function ff_type($nid) {
  /*
    Returns the value of the 'type' field in the node table for the given nid
  */
  
  $s = "SELECT type FROM {node} WHERE nid = %d LIMIT 1";
  $r = db_query($s, $nid);
  if (db_affected_rows($r)==1) {
    return db_result($r);
  } else {
    return;
  }
  
}