<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Thu, 08/21/2008 - 10:32
 * View: recent_news
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   recent_news, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $edit -- Display a link to edit the node. Enter the text of this link into the option field; if blank the default "Edit" will be used.
 * $edit_label -- The assigned label for $edit
 *
 * This function goes in your views-list-recent_news.tpl.php file
 */
 
 
  ?>

  <?php print $title?> <?php if ($edit) { print '('.$edit.')'; } ?>


