<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Thu, 08/28/2008 - 13:03
 * View: photo_galleries
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   photo_galleries, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $field_image_fid -- 
 * $field_image_fid_label -- The assigned label for $field_image_fid
 *
 * This function goes in your views-list-photo_galleries.tpl.php file
 */
 
 
 //now we add the stylesheet...
  
  ?>



<div class="view-field view-data-field-image-fid">
  <?php print $field_image_fid?>
</div>

