<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Fri, 08/01/2008 - 12:31
 * View: homepage_ads
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   homepage_ads, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $field_image_fid -- 
 * $field_image_fid_label -- The assigned label for $field_image_fid
 * $field_link_url -- 
 * $field_link_url_label -- The assigned label for $field_link_url
 *
 * This function goes in your views-list-homepage_ads.tpl.php file
 
stdClass Object
(
    [nid] => 2108
    [node_sticky] => 0
    [node_changed_changed] => 1217619557
    [node_title] => Projects Enhancing the Campus and Neighborhood
    [node_changed] => 1217619557
    [node_data_field_teaser_field_teaser_value] => <p>A number of <a href="features/projects-enhancing-campus-and-neighborhood">construction projects</a> in and around the Augustana campus are currently underway. More than $35 million is being invested in constructing and remodeling buildings on Augustana's campus, as well as across the street at Sioux Falls Seminary and Our Savior's Lutheran Church.</p>
    [node_data_field_teaser_field_teaser_format] => 3
    [node_data_field_image_field_image_fid] => 18
    [node_data_field_image_field_image_title] => ad3-contstruction.png
    [node_data_field_image_field_image_alt] => ad3-contstruction.png
    [node_data_field_link_field_link_url] => 
    [node_data_field_link_field_link_title] => 
    [node_data_field_link_field_link_attributes] => a:0:{}
 */
 //now we add the stylesheet...
 //dprint_r($node);
 ?>
 
<?php $file = _imagefield_file_load($node->node_data_field_image_field_image_fid); ?>
<?php $img = theme('imagecache', 'homepage_ad', $file['filepath'], $node->node_title,$node->node_title,array('width' => '240','height' => '136'));?>
<?php 

if ($node->node_data_field_link_field_link_url) {
	if (file_exists($file['filepath'])) { 
		print l($img, $node->node_data_field_link_field_link_url, null, null, null, true, true); 
	}
	?>
	<h5><?php print l($node->node_title, $node->node_data_field_link_field_link_url, null, null, null, true, true);  ?> <?php if ($edit) { print '<span class="edit-small">('.$edit.')</span>'; } ?></h5>

 <?php
} else {
	if (file_exists($file['filepath'])) { 
		print l($img, "node/$node->nid", null, null, null, true, true); 
	} ?>
	<h5><?php print l($node->node_title, "node/$node->nid", null, null, null, true, true);  ?> <?php if ($edit) { print '<span class="edit-small">('.$edit.')</span>'; } ?></h5>

<?php } ?>

<?php

print $node->node_data_field_teaser_field_teaser_value;

//print l("Add new", "node/add/homepage_ad", null,'destination=node', null, true, true); 
 ?>


 
 



