<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Sun, 06/15/2008 - 01:14
 * View: channel_image
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   channel_image, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $field_image_fid -- 
 * $field_image_fid_label -- The assigned label for $field_image_fid
 *
 * This function goes in your views-list-channel_image.tpl.php file
 */
 
 
 //now we add the stylesheet...

  ?>

<?php $file = _imagefield_file_load($node->node_data_field_image_field_image_fid); ?>
  <?php $img = theme('imagecache', 'channel', $file['filepath'], $node->node_title,$node->node_title);?>
 <?php if (file_exists($file['filepath'])) { ?>

 <?php if ($node->node_data_field_body_field_body_value) { ?> 
 <?php print l($img, "node/$node->nid", null, null, null, true, true); ?>
 <?php } else { ?>
 <?php print $img; ?>
  <?php } ?>

 <?php } ?>
